modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="metal_works"
version="1.2.0"
displayName="Metal Works"
credits="LicitLettuce (Game Design, Artist, Programmer), That_Bubba_Guy (Assets & Models), Im_Dolos (Tester, Concepts, & Contributor), WilliamExists (Contributor), Milo (Contributor)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/metal-works"
logoFile="logo.png"
authors="LicitLettuce, That Bubba Guy, Im_Dolos"
description="Adds vanilla-styled metals with distinct functions and some deco!"

[[dependencies.metal_works]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"