modLoader="javafml"
loaderVersion="[47,)"
license="Lettuce License V1"

[[mods]]
modId="metal_works"
version="1.0.0"
displayName="Metal Works"
credits="Mod By Licit Lettuce"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/metal-works"
logoFile="logo.png"
authors="Licit Lettuce, The Bubba Guy"
description="Adds vanilla-styled metals with distinct functions and some deco"

[[dependencies.balanced_crates]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"