modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="LicitLettuce (Game Design, Artist, Programmer), Im_Dolos (Tester, Concepts, & Documentation)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/metal-works"
logoFile="logo.png"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="blueprint"
type="required"
versionRange="[${blueprint_mod_version},)"
ordering="AFTER"
side="BOTH"
